# Generated by Django 5.2.6 on 2025-09-12 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('columns_web1', models.JSONField(default=list)),
                ('columns_desktop', models.JSONField(default=list)),
                ('join_key_web1', models.CharField(max_length=120)),
                ('join_key_desktop', models.CharField(max_length=120)),
                ('join_type', models.CharField(default='outer', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.configcategory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'category', 'name')},
            },
        ),
    ]
