# Generated by Django 5.2.6 on 2025-09-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0002_keys_to_json_safe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compareconfig',
            name='join_key_desktop',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='compareconfig',
            name='join_key_web1',
            field=models.JSONField(default=list),
        ),
    ]
