# Generated by Django 5.2.6 on 2025-09-12 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configs', '0001_initial'),
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('diff_rows', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configs.compareconfig')),
                ('dataset_desktop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='datasets.dataset')),
                ('dataset_web1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='datasets.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='CompareResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparisons.comparerun')),
            ],
        ),
    ]
