# Generated by Django 5.2.6 on 2025-09-12 23:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparerun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comparerun',
            name='export_csv',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='comparerun',
            name='export_xlsx',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
