# Generated by Django 5.2.6 on 2025-09-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0002_comparerun_created_at_comparerun_export_csv_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comparerun',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='comparerun',
            name='notes',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='comparerun',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Titre'),
        ),
    ]
